### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by sbandx** [michaelmano/WinterM#1]
[Enter steps to reproduce:]

1. Opened winterm at project directory with file selected: 
    this worked the first time
2. Attempted to open second winterm in same location

Crashed:

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [winterm](https://github.com/michaelmano/WinterM) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At E:\Coding\.atom\packages\winterm\lib\winterm.coffee:27

TypeError: Cannot read property 'file' of undefined
    at Object.isComing (/packages/winterm/lib/winterm.coffee:27:10)
    at /packages/winterm/lib/winterm.coffee:18:65)
    at CommandRegistry.handleCommandEvent (E:/Coding/Atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (E:/Coding/Atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (E:/Coding/Atom/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (E:/Coding/Atom/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -5:50.3.0 winterm:isComing (atom-pane.pane.active)
     -4:44.2.0 application:add-project-folder (atom-pane.pane.active)
  3x -3:35.4.0 winterm:isComing (atom-pane.pane.active)
```

### Non-Core Packages

```
Extempore-Atom 0.3.2 
tidalcycles 0.12.1 
winterm 0.2.0 
```

**Comment by sbandx** [comment]
Reproduced this by clicking on the parent folder of the previous entry, same crash.
Can't open more than one winterm at same exact location?

**Comment by michaelmano** [comment]
@sbandx Thanks for this, I will get onto it now 👍 

EDIT: Fixed and released a new version, Since you took the time to actually write an issue for this I see people are still using this or at least trying it out. I will work on a new release which is cleaner and faster loading. Thank you for taking the time. :)
